version: "3"

services:
  localstack:
    container_name: lean_localstack
    image: localstack/localstack
    ports:
      - "4563-4599:4563-4599"
      - "8055:8080"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "./.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - lean-network

networks:
  default:
    driver: bridge
  lean-network:
    external: true
